name: Build and Release TotemMod

on:
  push:
    tags:
      - 'v*'  # Triggers only when you push a version tag like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 21

    - name: Make Gradle wrapper executable
      run: chmod +x ./gradlew

    - name: Build mod
      run: ./gradlew build

    - name: Upload jar to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: build/libs/*.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
